[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Library dependencies
lib_deps =
  ; Tidak ada library eksternal — semua API bawaan Arduino/ESP32

; Build flags
build_flags =
  -DCORE_DEBUG_LEVEL=3

; Serial monitor
monitor_speed = 115200
